/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import dao.CategorieDao;
import dao.ProduitDao;
import dao.PromotionDAO;
import entite.Promotion;
import javax.swing.JTextField;
import utils.DisplayPromo;
import utils.DisplaySearchPromo;

import de.javasoft.plaf.synthetica.SyntheticaBlueLightLookAndFeel;
import java.awt.Point;
import java.sql.ResultSet;
import java.sql.SQLException;

import java.util.Date;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javafx.stage.Screen;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
/**
 *
 * @author Hakim
 */
public class PromoFrame extends javax.swing.JFrame {
       ProduitDao proDao = new ProduitDao();
    
    public PromoFrame() throws UnsupportedLookAndFeelException, ParseException {
        UIManager.setLookAndFeel(new SyntheticaBlueLightLookAndFeel());
        initComponents();
        loadAllName();
        this.setResizable(false);
       
    }
private void loadAllName() {
        ProduitDao c = new ProduitDao();
        try {
            ResultSet res = c.getAllNameProduit();
            while (res.next()) {
                cbProduit.addItem(res.getString(1));
            }
        } catch (SQLException ex) {
            Logger.getLogger(Responsable.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        search = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        lnom = new javax.swing.JLabel();
        tfnom = new javax.swing.JTextField();
        lreduction = new javax.swing.JLabel();
        lidp = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        tableajout = new javax.swing.JTable();
        tfreduction = new javax.swing.JTextField();
        debut = new com.toedter.calendar.JDateChooser();
        fin = new com.toedter.calendar.JDateChooser();
        ld = new javax.swing.JLabel();
        lf = new javax.swing.JLabel();
        cbProduit = new javax.swing.JComboBox();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablesupp = new javax.swing.JTable();
        jButton4 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tableupdate = new javax.swing.JTable();
        jButtonUpdate = new javax.swing.JButton();
        IMessage2 = new javax.swing.JLabel();
        tfnom1 = new javax.swing.JTextField();
        lnom1 = new javax.swing.JLabel();
        lreduction1 = new javax.swing.JLabel();
        tfreduction1 = new javax.swing.JTextField();
        lidp1 = new javax.swing.JLabel();
        ld1 = new javax.swing.JLabel();
        debut1 = new com.toedter.calendar.JDateChooser();
        lf1 = new javax.swing.JLabel();
        fin1 = new com.toedter.calendar.JDateChooser();
        tfid = new javax.swing.JTextField();
        lid = new javax.swing.JLabel();
        cbbProd = new javax.swing.JComboBox();
        jToggleButton1 = new javax.swing.JToggleButton();
        lrecherche = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchActionPerformed(evt);
            }
        });
        search.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                searchKeyReleased(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Wide Latin", 1, 18)); // NOI18N
        jLabel2.setText("Gestion promotion");

        jTabbedPane2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jPanel3.setLayout(null);

        lnom.setText("Nom");
        jPanel3.add(lnom);
        lnom.setBounds(20, 30, 40, 14);
        jPanel3.add(tfnom);
        tfnom.setBounds(90, 30, 130, 20);

        lreduction.setText("Reduction");
        jPanel3.add(lreduction);
        lreduction.setBounds(0, 70, 60, 14);

        lidp.setText("nom  produit");
        jPanel3.add(lidp);
        lidp.setBounds(0, 110, 70, 14);

        jButton1.setText("Ajouter");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton1);
        jButton1.setBounds(40, 280, 170, 40);

        tableajout.setModel(new DisplayPromo());
        jScrollPane5.setViewportView(tableajout);

        jPanel3.add(jScrollPane5);
        jScrollPane5.setBounds(270, 10, 340, 370);

        tfreduction.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfreductionActionPerformed(evt);
            }
        });
        jPanel3.add(tfreduction);
        tfreduction.setBounds(90, 70, 130, 20);

        debut.setDateFormatString("yyyy-MM-dd");
        jPanel3.add(debut);
        debut.setBounds(90, 150, 130, 20);

        fin.setDateFormatString("yyyy-MM-dd");
        jPanel3.add(fin);
        fin.setBounds(90, 190, 130, 20);

        ld.setText("Date debut");
        jPanel3.add(ld);
        ld.setBounds(0, 150, 70, 14);

        lf.setText("Date fin");
        jPanel3.add(lf);
        lf.setBounds(0, 200, 60, 14);

        cbProduit.setModel(new javax.swing.DefaultComboBoxModel(new String[] {  }));
        cbProduit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbProduitActionPerformed(evt);
            }
        });
        jPanel3.add(cbProduit);
        cbProduit.setBounds(90, 110, 130, 20);

        jTabbedPane2.addTab("Ajouter Promotion ", jPanel3);

        tablesupp.setModel(new DisplayPromo());
        tablesupp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablesuppMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tablesuppMouseEntered(evt);
            }
        });
        jScrollPane2.setViewportView(tablesupp);

        jButton4.setText("supprimer");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(201, 201, 201)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(101, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5))
        );

        jTabbedPane2.addTab("Supprimer Promotion ", jPanel4);

        tableupdate.setModel(new DisplayPromo());
        tableupdate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableupdateMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(tableupdate);

        jButtonUpdate.setText("modifier");
        jButtonUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUpdateActionPerformed(evt);
            }
        });

        IMessage2.setForeground(new java.awt.Color(255, 0, 0));

        lnom1.setText("Nom");

        lreduction1.setText("Reduction");

        tfreduction1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfreduction1ActionPerformed(evt);
            }
        });

        lidp1.setText("Id produit");

        ld1.setText("debut");

        debut1.setDateFormatString("yyyy-MM-dd");

        lf1.setText("fin");

        fin1.setDateFormatString("yyyy-MM-dd");

        tfid.setEnabled(false);

        lid.setText("id");

        cbbProd.setModel(new javax.swing.DefaultComboBoxModel(new String[] { }));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(lreduction1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(tfreduction1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(lidp1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbbProd, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lnom1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lid, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(10, 10, 10)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(tfid)
                                    .addComponent(tfnom1, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addComponent(ld1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(26, 26, 26)
                                        .addComponent(debut1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addComponent(lf1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(26, 26, 26)
                                        .addComponent(fin1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(jButtonUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addComponent(IMessage2, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lid))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lnom1)
                            .addComponent(tfnom1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lreduction1)
                            .addComponent(tfreduction1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(17, 17, 17)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lidp1)
                            .addComponent(cbbProd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(23, 23, 23)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ld1)
                            .addComponent(debut1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lf1)
                            .addComponent(fin1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jButtonUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21))
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(IMessage2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Modifier Promotion", jPanel5);

        jToggleButton1.setText("Move To");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });

        lrecherche.setText("recherche");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(43, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lrecherche, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(search, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jToggleButton1)))
                .addGap(51, 51, 51))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jToggleButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lrecherche, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(search, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 401, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void searchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchKeyReleased
        tableupdate.setModel(new DisplaySearchPromo(search.getText()));
        tableajout.setModel(new DisplaySearchPromo(search.getText()));
        tablesupp.setModel(new DisplaySearchPromo(search.getText()));
    }//GEN-LAST:event_searchKeyReleased

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
 if (tfnom.equals("") || (tfreduction.getText().equals("")) || (cbProduit.getSelectedItem().toString().equals("")) || (((JTextField)debut.getDateEditor().getUiComponent()).getText().equals("")) || (((JTextField)fin.getDateEditor().getUiComponent()).getText().equals(""))) {
            JOptionPane.showMessageDialog(this, "Veuillez remplir tous les champs", "attention", JOptionPane.ERROR_MESSAGE, null);
            return;
        }
       
        new PromotionDAO().addPromotion(new Promotion(tfnom.getText(), Integer.parseInt(tfreduction.getText()), ((JTextField)debut.getDateEditor().getUiComponent()).getText(), ((JTextField)fin.getDateEditor().getUiComponent()).getText(),proDao.getIdOfProduit(cbProduit.getSelectedItem().toString()),cbProduit.getSelectedItem().toString() ));
        tableajout.setModel(new DisplayPromo());
        tablesupp.setModel(new DisplayPromo());
        tableupdate.setModel(new DisplayPromo());
        tfnom.setText("");
        tfreduction.setText("");
        cbProduit.setModel(new javax.swing.DefaultComboBoxModel(new String[] {  }));
        ((JTextField)debut.getDateEditor().getUiComponent()).setText("");
        ((JTextField)fin.getDateEditor().getUiComponent()).setText("");

    }//GEN-LAST:event_jButton1ActionPerformed

    private void tablesuppMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablesuppMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tablesuppMouseClicked

    private void tablesuppMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablesuppMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_tablesuppMouseEntered

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
new PromotionDAO().removePromotionById(Integer.parseInt(tablesupp.getValueAt(tablesupp.getSelectedRow(), 0).toString()));
tableajout.setModel(new DisplayPromo());
        tablesupp.setModel(new DisplayPromo());
        tableupdate.setModel(new DisplayPromo());
    }//GEN-LAST:event_jButton4ActionPerformed

    private void tableupdateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableupdateMouseClicked
        tfid.setText(tableupdate.getValueAt(tableupdate.getSelectedRow(), 0).toString());
        tfnom1.setText(tableupdate.getValueAt(tableupdate.getSelectedRow(), 1).toString());
        tfreduction1.setText(tableupdate.getValueAt(tableupdate.getSelectedRow(), 2).toString());       
        cbbProd.setModel(new javax.swing.DefaultComboBoxModel(new String[] { tableupdate.getValueAt(tableupdate.getSelectedRow(), 3).toString()  }));
        DateFormat format = new SimpleDateFormat("yyyy-MM-dd");
        try {
            Date datee =  format.parse((String) tableupdate.getValueAt(tableupdate.getSelectedRow(), 4).toString());
            debut1.setDate(datee);
        } catch (ParseException ex) {
            Logger.getLogger(PromoFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        try {
            Date dateee =  format.parse((String) tableupdate.getValueAt(tableupdate.getSelectedRow(), 5).toString());
            fin1.setDate(dateee);
        } catch (ParseException ex) {
            Logger.getLogger(PromoFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }//GEN-LAST:event_tableupdateMouseClicked

    private void jButtonUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUpdateActionPerformed
    if (tfnom1.getText().equals("") || (tfreduction1.getText().equals("")) || (cbbProd.getSelectedItem().toString().equals("")) || (((JTextField)debut1.getDateEditor().getUiComponent()).getText().equals("")) || (((JTextField)fin1.getDateEditor().getUiComponent()).getText().equals(""))) {
            JOptionPane.showMessageDialog(this, "Veuillez remplir tous les champs", "attention", JOptionPane.ERROR_MESSAGE, null);
            return;
        }       
        
        
        new PromotionDAO().updatePromotion(new Promotion(Integer.parseInt(tfid.getText()), tfnom1.getText(), Integer.parseInt(tfreduction1.getText()), ((JTextField)debut1.getDateEditor().getUiComponent()).getText(), ((JTextField)fin1.getDateEditor().getUiComponent()).getText(), proDao.getIdOfProduit(cbProduit.getSelectedItem().toString()),cbProduit.getSelectedItem().toString() ));
        tableajout.setModel(new DisplayPromo());
        tablesupp.setModel(new DisplayPromo());
        tableupdate.setModel(new DisplayPromo());
        tfid.setText("");
         tfnom1.setText("");
        tfreduction1.setText("");
         cbbProd.setModel(new javax.swing.DefaultComboBoxModel(new String[] {  }));
        ((JTextField)debut1.getDateEditor().getUiComponent()).setText("");
        ((JTextField)fin1.getDateEditor().getUiComponent()).setText("");
    }//GEN-LAST:event_jButtonUpdateActionPerformed

    private void tfreductionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfreductionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfreductionActionPerformed

    private void searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchActionPerformed

    private void tfreduction1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfreduction1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfreduction1ActionPerformed

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        this.hide();
        new PubFrame().show();
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void cbProduitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbProduitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbProduitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PromoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PromoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PromoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PromoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new PromoFrame().setVisible(true);
                } catch (UnsupportedLookAndFeelException ex) {
                    Logger.getLogger(PromoFrame.class.getName()).log(Level.SEVERE, null, ex);
                } catch (ParseException ex) {
                    Logger.getLogger(PromoFrame.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel IMessage2;
    private javax.swing.JComboBox cbProduit;
    private javax.swing.JComboBox cbbProd;
    private com.toedter.calendar.JDateChooser debut;
    private com.toedter.calendar.JDateChooser debut1;
    private com.toedter.calendar.JDateChooser fin;
    private com.toedter.calendar.JDateChooser fin1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButtonUpdate;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JLabel ld;
    private javax.swing.JLabel ld1;
    private javax.swing.JLabel lf;
    private javax.swing.JLabel lf1;
    private javax.swing.JLabel lid;
    private javax.swing.JLabel lidp;
    private javax.swing.JLabel lidp1;
    private javax.swing.JLabel lnom;
    private javax.swing.JLabel lnom1;
    private javax.swing.JLabel lrecherche;
    private javax.swing.JLabel lreduction;
    private javax.swing.JLabel lreduction1;
    private javax.swing.JTextField search;
    private javax.swing.JTable tableajout;
    private javax.swing.JTable tablesupp;
    private javax.swing.JTable tableupdate;
    private javax.swing.JTextField tfid;
    private javax.swing.JTextField tfnom;
    private javax.swing.JTextField tfnom1;
    private javax.swing.JTextField tfreduction;
    private javax.swing.JTextField tfreduction1;
    // End of variables declaration//GEN-END:variables
}
