/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import com.sun.xml.internal.messaging.saaj.util.ByteInputStream;
import dao.CategorieDao;
import dao.MediaDao;
import dao.ProduitDao;
import entite.Categorie;
import entite.Produit;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Component;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.WindowEvent;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.InputStream;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.ParseException;
import java.util.ArrayList;
import java.util.List;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JRadioButton;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.SwingConstants;
import javax.swing.event.ListSelectionEvent;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableCellRenderer;
import static org.hamcrest.CoreMatchers.is;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.CategoryPlot;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.CategoryDataset;
import org.jfree.data.category.DefaultCategoryDataset;
import utils.ProfilePictruesManager;

/**
 *
 * @author adouni
 */
public class Responsable extends javax.swing.JDialog {
    
    ProduitDao produitdao = new ProduitDao();
    int idCat;
    public int idmedia;
    //   private JTable table1;
    // private  TableModel tab;
    //private Object datasett;
    //  private CategoryDataset datasett;

    @Override
    public void remove(Component comp) {
        super.remove(comp); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * Creates new form Responsable
     */
    public Responsable(java.awt.Frame parent, boolean modal) throws SQLException {
        super(parent, modal);
        initComponents();
        loaddata();
        loadAllName();
        
    }
    
    private void loaddata() throws SQLException {
        try {
            
            TableModel tab = new TableModel(produitdao.findAll());
            jTableproduit.setModel(tab);
            
        } catch (Exception ex) {
            System.out.println(ex.getMessage());
        }
    }
    
    private String[] type() {
        List<String> ls = new ArrayList<>();
        CategorieDao c = new CategorieDao();
        String[] tab = {""};
        ls = c.DisplayAllName();
        for (int i = 0; i < ls.size(); i++) {
            System.out.println(ls.get(i).toString());
            tab[i] = ls.get(i).toString();
        }
        return tab;
    }
    
    private void loadAllName() {
        CategorieDao c = new CategorieDao();
        try {
            ResultSet res = c.getAllNameCat();
            while (res.next()) {
                cbCat.addItem(res.getString(1));
            }
        } catch (SQLException ex) {
            Logger.getLogger(Responsable.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        TFRefer = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        TFNOM = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        TADescription = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        TFprix = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        Tfquntite = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        cbotype = new javax.swing.JComboBox();
        jButton_Browser = new javax.swing.JButton();
        jLabel_img = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jBajouter = new javax.swing.JButton();
        jButton_Modifier = new javax.swing.JButton();
        jButton_supprimer = new javax.swing.JButton();
        jButton_clear = new javax.swing.JButton();
        jButton_rechercher = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        bCategorie = new javax.swing.JButton();
        cbCat = new javax.swing.JComboBox();
        labelPrixD = new java.awt.Label();
        tfPrixGros = new java.awt.TextField();
        labelPrixD1 = new java.awt.Label();
        tfPrixDetaille = new java.awt.TextField();
        jToolBar1 = new javax.swing.JToolBar();
        jPaneltab = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableproduit = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        jLabel6.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 0, 51));
        jLabel6.setText("type :");

        jMenuItem1.setText("jMenuItem1");

        jMenu3.setText("jMenu3");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "gestion de stock", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 3, 12), new java.awt.Color(255, 0, 0))); // NOI18N
        jPanel1.setToolTipText("");

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel1.setText("Reference :");

        TFRefer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFReferActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel2.setText("Nom :");

        TFNOM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFNOMActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel3.setText("Description : ");

        TADescription.setColumns(20);
        TADescription.setRows(5);
        jScrollPane2.setViewportView(TADescription);

        jLabel4.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel4.setText("Prix :");

        TFprix.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFprixActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel5.setText("quantite :");

        Tfquntite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TfquntiteActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel7.setText("type :");

        jLabel8.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel8.setText("Categorie :");

        cbotype.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Homme", "Femme", "Enfant" }));
        cbotype.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbotypeItemStateChanged(evt);
            }
        });
        cbotype.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbotypeActionPerformed(evt);
            }
        });

        jButton_Browser.setText("Browser");
        jButton_Browser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_BrowserActionPerformed(evt);
            }
        });

        jLabel_img.setBackground(new java.awt.Color(204, 255, 204));
        jLabel_img.setForeground(new java.awt.Color(255, 204, 204));
        jLabel_img.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/stock-vector-four-modern-clothes-icons-360838346.jpg"))); // NOI18N

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jBajouter.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Button-Add-icon.png"))); // NOI18N
        jBajouter.setText("Ajouter");
        jBajouter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBajouterActionPerformed(evt);
            }
        });

        jButton_Modifier.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/edit-icon.png"))); // NOI18N
        jButton_Modifier.setText("Modifier");
        jButton_Modifier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ModifierActionPerformed(evt);
            }
        });

        jButton_supprimer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Button-Close-icon.png"))); // NOI18N
        jButton_supprimer.setText("Supprimer");
        jButton_supprimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_supprimerActionPerformed(evt);
            }
        });

        jButton_clear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Clear-icon.png"))); // NOI18N
        jButton_clear.setText("Reset");
        jButton_clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_clearActionPerformed(evt);
            }
        });

        jButton_rechercher.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/search-icon.png"))); // NOI18N
        jButton_rechercher.setText("Rechercher");
        jButton_rechercher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_rechercherActionPerformed(evt);
            }
        });

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/chart-icon (1).png"))); // NOI18N
        jButton1.setText("statistique");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton_rechercher, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton_clear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton_Modifier, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton_supprimer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBajouter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(194, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jBajouter, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton_supprimer)
                .addGap(16, 16, 16)
                .addComponent(jButton_Modifier)
                .addGap(24, 24, 24)
                .addComponent(jButton_clear)
                .addGap(18, 18, 18)
                .addComponent(jButton_rechercher)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        bCategorie.setText("Gérer Categorie");
        bCategorie.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bCategorieMouseClicked(evt);
            }
        });

        cbCat.setModel(new javax.swing.DefaultComboBoxModel());
        cbCat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cbCatMouseClicked(evt);
            }
        });
        cbCat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbCatActionPerformed(evt);
            }
        });

        labelPrixD.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        labelPrixD.setText("Prix Detaille:");

        tfPrixGros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfPrixGrosActionPerformed(evt);
            }
        });

        labelPrixD1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        labelPrixD1.setText("prixGros :");

        tfPrixDetaille.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfPrixDetailleActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(labelPrixD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(labelPrixD1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbotype, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(TFRefer, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TFNOM, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(TFprix, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(Tfquntite, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(cbCat, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(bCategorie, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addComponent(tfPrixDetaille, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfPrixGros, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(jLabel_img, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(101, 101, 101)
                        .addComponent(jButton_Browser, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(31, 31, 31)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(148, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TFRefer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TFNOM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(TFprix, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(20, 20, 20)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(labelPrixD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tfPrixDetaille, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel_img, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tfPrixGros, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(labelPrixD1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(21, 21, 21)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel5)
                                    .addComponent(Tfquntite, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(21, 21, 21)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cbotype, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(bCategorie)
                                    .addComponent(cbCat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jButton_Browser, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        jToolBar1.setRollover(true);

        jPaneltab.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jTableproduit.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTableproduit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableproduitMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableproduit);

        javax.swing.GroupLayout jPaneltabLayout = new javax.swing.GroupLayout(jPaneltab);
        jPaneltab.setLayout(jPaneltabLayout);
        jPaneltabLayout.setHorizontalGroup(
            jPaneltabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPaneltabLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1203, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPaneltabLayout.setVerticalGroup(
            jPaneltabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPaneltabLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE)
                .addContainerGap())
        );

        jMenuBar1.setEnabled(false);
        jMenuBar1.setFocusable(false);

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu2ActionPerformed(evt);
            }
        });
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPaneltab, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(1125, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPaneltab, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(550, Short.MAX_VALUE))
        );

        jPanel1.getAccessibleContext().setAccessibleName("Gestion de stock");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBajouterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBajouterActionPerformed
        
        Produit p = new Produit();
        CategorieDao catDao = new CategorieDao();
        Categorie c = new Categorie();
        
        try {
            p.setImage(idmedia);
            p.setReference(TFRefer.getText());
            p.setNom(TFNOM.getText());
            p.setDescription(TADescription.getText());
            p.setPrix((Float.parseFloat(TFprix.getText())));
            p.setQuantite(Integer.parseInt(Tfquntite.getText()));
            p.setType(cbotype.getSelectedItem().toString());
            if (cbCat.isVisible()) {
                c = catDao.findCategorieByNon(cbCat.getSelectedItem().toString());
                idCat = c.getId();
            }
            p.setIdCat(idCat);
            p.setCategorie(cbCat.getSelectedItem().toString());
            p.setPrixDetaille(Double.parseDouble(tfPrixDetaille.getText()));
            p.setPrixGros(Double.parseDouble(tfPrixGros.getText()));
            
            produitdao.add(p,idmedia);
            JOptionPane.showMessageDialog(null, "Ajouter avec succès ");
            
            loaddata();
            clearInputBoxes();
        } catch (SQLException ex) {
            Logger.getLogger(Responsable.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jBajouterActionPerformed
    private void clearInputBoxes() {
        TFRefer.setText("");
        TFNOM.setText("");
        TADescription.setText("");
        TFprix.setText("");
        Tfquntite.setText("");
        
        cbotype.setSelectedItem("");
        cbCat.setName("");
        
    }
    

    private void jTableproduitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableproduitMouseClicked
        
        jTableproduit.getSelectionModel().addListSelectionListener((ListSelectionEvent event) -> {
            try {
                if (jTableproduit.getSelectedRow() >= 0) {
                    Object ref = jTableproduit.getValueAt(jTableproduit.getSelectedRow(), 0);
                    Object full_name = jTableproduit.getValueAt(jTableproduit.getSelectedRow(), 1);
                    Object descp = jTableproduit.getValueAt(jTableproduit.getSelectedRow(), 2);
                    Object prix = jTableproduit.getValueAt(jTableproduit.getSelectedRow(), 3);
                    Object qunt = jTableproduit.getValueAt(jTableproduit.getSelectedRow(), 4);
                    Object type = jTableproduit.getValueAt(jTableproduit.getSelectedRow(), 5);
                    Object categ = jTableproduit.getValueAt(jTableproduit.getSelectedRow(), 6);
                    //    Object Image = jTableproduit.getValueAt(jTableproduit.getSelectedRow(), 7);

                    TFRefer.setText(ref.toString());
                    TFNOM.setText(full_name.toString());
                    TADescription.setText(descp.toString());
                    TFprix.setText(prix.toString());
                    Tfquntite.setText(qunt.toString());
                    cbotype.setSelectedItem(type.toString());
                    cbCat.setSelectedItem(categ.toString());
                    jLabel_img.setText(s);
                    
                }
            } catch (Exception ex) {
                System.out.println(ex.getMessage());
            }
        });
        
        DefaultTableCellRenderer rightRenderer = new DefaultTableCellRenderer();
        rightRenderer.setHorizontalAlignment(SwingConstants.LEFT);
        jTableproduit.getColumnModel().getColumn(0).setCellRenderer(rightRenderer);
    }//GEN-LAST:event_jTableproduitMouseClicked

    private void cbotypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbotypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbotypeActionPerformed

    private void TfquntiteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TfquntiteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TfquntiteActionPerformed

    private void TFprixActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFprixActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TFprixActionPerformed

    private void TFNOMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFNOMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TFNOMActionPerformed

    private void TFReferActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFReferActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TFReferActionPerformed

    private void jButton_ModifierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ModifierActionPerformed
        Produit p = new Produit();
        ProduitDao prodDao = new ProduitDao();
        CategorieDao catDao = new CategorieDao();
        Categorie c = new Categorie();
        try {
            
            p.setReference(TFRefer.getText());
            p.setNom(TFNOM.getText());
            p.setDescription(TADescription.getText());
            p.setPrix((Float.parseFloat(TFprix.getText())));
            p.setQuantite(Integer.parseInt(Tfquntite.getText()));
            p.setType(cbotype.getSelectedItem().toString());
            if (cbCat.isVisible()) {
                c = catDao.findCategorieByNon(cbCat.getSelectedItem().toString());
                idCat = c.getId();
            }
            p.setIdCat(idCat);
            p.setCategorie(cbCat.getSelectedItem().toString());
            p.setPrixDetaille(Double.parseDouble(tfPrixDetaille.getText()));
            p.setPrixGros(Double.parseDouble(tfPrixGros.getText()));
            prodDao.update(p);
            loaddata();
            
            JOptionPane.showMessageDialog(null, "modifier avec succès ");
        } catch (SQLException ex) {
            Logger.getLogger(Responsable.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton_ModifierActionPerformed

    private void jButton_supprimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_supprimerActionPerformed
        produitdao.removeByRef(TFRefer.getText());
        JOptionPane.showMessageDialog(null, "Supprimer avec succès ");
        
        try {
            loaddata();
        } catch (SQLException ex) {
            Logger.getLogger(Responsable.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jButton_supprimerActionPerformed

    private void jButton_clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_clearActionPerformed
        clearInputBoxes();
    }//GEN-LAST:event_jButton_clearActionPerformed

    private void jButton_rechercherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_rechercherActionPerformed
        
        try {
            
            String[] btns = {"reference ", "Nom", "prix", "Quntite", "Type", "Categorie"};
            String cle = (String) JOptionPane.showInputDialog(null,
                    "Veuillez indiquer le critère de recherche !", "Recherche",
                    JOptionPane.QUESTION_MESSAGE, null, btns, btns[1]);
            String val = "";
            TableModel tab;
            switch (cle) {
                case "reference":
                    val = JOptionPane.showInputDialog(null, cle, "recherche",
                            JOptionPane.QUESTION_MESSAGE);
                    tab = new TableModel((List<Produit>) produitdao.findById(val));
                    jTableproduit.setModel(tab);
                    break;
                
                case "Nom":
                    val = JOptionPane.showInputDialog(null, cle, "recherche",
                            JOptionPane.QUESTION_MESSAGE);
                    
                    tab = new TableModel(produitdao.findAll2(val));
                    jTableproduit.setModel(tab);
                    break;
                case "prix":
                    val = JOptionPane.showInputDialog(null, cle, "recherche",
                            JOptionPane.QUESTION_MESSAGE);
                    
                    tab = new TableModel(produitdao.findAll2(val));
                    jTableproduit.setModel(tab);
                    break;
                case "Quntite":
                    val = JOptionPane.showInputDialog(null, cle, "recherche",
                            JOptionPane.QUESTION_MESSAGE);
                    
                    tab = new TableModel(produitdao.findAll2(val));
                    jTableproduit.setModel(tab);
                    break;
                
                case "Type":
                    val = JOptionPane.showInputDialog(null, cle, "recherche",
                            JOptionPane.QUESTION_MESSAGE);
                    
                    tab = new TableModel(produitdao.findAll2(val));
                    jTableproduit.setModel(tab);
                    break;
                
                case "Categorie":
                    val = JOptionPane.showInputDialog(null, cle, "recherche",
                            JOptionPane.QUESTION_MESSAGE);
                    
                    tab = new TableModel(produitdao.findAll2(val));
                    jTableproduit.setModel(tab);
                    break;
                default:
                    
                    break;
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "don't do that again");
        }
        

    }//GEN-LAST:event_jButton_rechercherActionPerformed

/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//button to browse the image into jlabel

    private void jButton_BrowserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_BrowserActionPerformed
        
        JFileChooser chooser = new JFileChooser(new File("C:\\"));
        chooser.removeChoosableFileFilter(chooser.getAcceptAllFileFilter());
        chooser.addChoosableFileFilter(new FileNameExtensionFilter("Images", "jpeg", "gif", "jpg", "png", "JPEG", "GIF", "JPG", "PNG"));
        chooser.setMultiSelectionEnabled(false);
        chooser.setVisible(true);
        chooser.showOpenDialog(null);
       // if (evt.getActionCommand().equalsIgnoreCase("ApproveSelection")) {
            ProfilePictruesManager pic = new ProfilePictruesManager();
            MediaDao medDao = new MediaDao();
            try {
                Image image = pic.changePicture(jLabel_img,chooser.getSelectedFile());
                idmedia = medDao.getDernierId();
            } catch (IOException ex) {
                Logger.getLogger(Responsable.class.getName()).log(Level.SEVERE, null, ex);
            } catch (InterruptedException ex) {
                Logger.getLogger(Responsable.class.getName()).log(Level.SEVERE, null, ex);
            } catch (ParseException ex) {
                Logger.getLogger(Responsable.class.getName()).log(Level.SEVERE, null, ex);
            }
            
       // } else if (evt.getActionCommand().equalsIgnoreCase("CancelSelection")) {
            
        //}        
        
    }//GEN-LAST:event_jButton_BrowserActionPerformed
    

    private void jMenu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu2ActionPerformed
    }//GEN-LAST:event_jMenu2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        statitstque stat = new statitstque();
        this.setVisible(false);
        stat.setVisible(true);

    }//GEN-LAST:event_jButton1ActionPerformed

    private void bCategorieMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bCategorieMouseClicked
        CategorieFrame cat = new CategorieFrame();
        cat.setVisible(true);
    }//GEN-LAST:event_bCategorieMouseClicked

    private void cbCatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbCatMouseClicked

    }//GEN-LAST:event_cbCatMouseClicked

    private void tfPrixGrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfPrixGrosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfPrixGrosActionPerformed

    private void tfPrixDetailleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfPrixDetailleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfPrixDetailleActionPerformed

    private void cbotypeItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbotypeItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_cbotypeItemStateChanged

    private void cbCatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbCatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbCatActionPerformed
//Methode To Resize The ImageIcon

    public ImageIcon ResizeImage(String imgPath) {
        ImageIcon MyImage = new ImageIcon(imgPath);
        Image img = MyImage.getImage();
        Image newImage = img.getScaledInstance(jLabel_img.getWidth(), jLabel_img.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon image = new ImageIcon(newImage);
        return image;
    }

    ///////////////////////////////////////////////////////////////////////////////////////////////////////////
    public void close() {
        WindowEvent theEvent = new WindowEvent(this, WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(theEvent);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Responsable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Responsable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Responsable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Responsable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Responsable dialog = null;
                try {
                    dialog = new Responsable(new javax.swing.JFrame(), true);
                } catch (SQLException ex) {
                    Logger.getLogger(Responsable.class.getName()).log(Level.SEVERE, null, ex);
                }
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    /////////////////////////////////////////////////////////////////////////////////////

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea TADescription;
    private javax.swing.JTextField TFNOM;
    private javax.swing.JTextField TFRefer;
    private javax.swing.JTextField TFprix;
    private javax.swing.JTextField Tfquntite;
    private javax.swing.JButton bCategorie;
    private javax.swing.JComboBox cbCat;
    private javax.swing.JComboBox cbotype;
    private javax.swing.JButton jBajouter;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton_Browser;
    private javax.swing.JButton jButton_Modifier;
    private javax.swing.JButton jButton_clear;
    private javax.swing.JButton jButton_rechercher;
    private javax.swing.JButton jButton_supprimer;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel_img;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPaneltab;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTableproduit;
    private javax.swing.JToolBar jToolBar1;
    private java.awt.Label labelPrixD;
    private java.awt.Label labelPrixD1;
    private java.awt.TextField tfPrixDetaille;
    private java.awt.TextField tfPrixGros;
    // End of variables declaration//GEN-END:variables
    String s;
    
}
